### ISSUE TITLE
TimeLimitExceededError issue when search the results

### ISSUE THREAD

**Issue by sayyedhanif1** [jeremycx/node-LDAP#109]
Hi,

client.search(config.LDAPServerConfig.ou,opts, function(err, resp) {
...

I am using this method for search the results

but it showing this err:
TimeLimitExceededError: Time Limit Exceeded

Please let me help to sort out the issue?

**Comment by jeremycx** [comment]
That's an error typically returned by the server when you send a query that would take too many resources to return. Try it with a more restrictive filter (return fewer results) and the error should not happen.
