### ISSUE TITLE
Can't install ldap-client

### ISSUE THREAD

**Issue by niyazagtc** [jeremycx/node-LDAP#110]
I tried installing the ldap client for nodejs on my local windows machine by running this command, npm install --save ldap-client.
I installed the OpenLDAP lcient libraries from here (http://www.openldap.org/software/download/) as tgz and exctracted that and put the folder in my project folder.

It gives the error as attached
![image](https://user-images.githubusercontent.com/15685819/37754340-1e2b3c22-2ddc-11e8-8666-ea12b3a8f477.png)

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1

Could you please advice whats wrong in my case?

Thanks

**Comment by jeremycx** [comment]
Sorry, there's no build support on Windows, but feel free to add some!
