### ISSUE TITLE
Possible binary data corruption with Active Directory?

### ISSUE THREAD

**Issue by Alaneor** [jeremycx/node-LDAP#44]
Hi,

I am trying to read the *objectGUID* binary property from Active Directory. For whatever reason, the data I am getting is not identical to the data I see in AD.
```
AD hex:      49 92 CE 93 25 F0 77 47 8A BF 22 74 01 8B A5 B2
Hex in Node: 49 FD    93 25 FD 77 47 FD FD 22 74 01 FD FD FD
```

Sometimes, one octet is missing, but always some other octets look like they have been corrupted somehow. I can't make anything out of this. I tried several ways of getting to the hex string and all of them give me incorrect data.

I have also tested this behaviour with one additional similar attribute, *msExchMailboxGuid*.

Here's the code I used to obtain that hex string in Node:
```js
// data is unmodified resultset returned from ldap.search()
var guid = data[0].objectGUID[0];
var buf = (new Buffer guid, 'binary').toString( 'hex' );
console.log( buf );
```
PS. When I read the property from PHP and convert the data to hex string with [bin2hex()](http://php.net/manual/en/function.bin2hex.php) I get correct results.

If you'd like me to try something out or provide more data just let me know, I have a test AD environment ready with full access.

Thanks for your help!

**Comment by Alaneor** [comment]
I just noticed that you are working on the NaN rewrite and aiming to bump to next major version. This might be an opportunity to revisit this issue.

I have found one js library which seems to be doing something we might use here. The solution to this problem could be an UTF-8 data validation.

The approach could be as follows:
1. See if the attribute data is a valid UTF-8 string (or array thereof)
1. If not, return the attribute data as buffer to keep the data from getting corrupted
1. If yes, convert data to standard JS string

The 1st point is the most tricky, but [utf-8-validate](https://github.com/websockets/utf-8-validate/blob/master/src/validation.cc) seems to be doing just that in C++. Perhaps we could extract some of the code into this library and use it to validate the data?

Since this approach might not be completely failsafe nor fast, perhaps there could be a configuration option to enable these checks on a global or per-request basis.

Reopening this, but if you find this proposal unsuitable, feel free to close. Thanks!

**Comment by jeremycx** [comment]
Can you confirm that the old ;binary suffix **ever** worked at all?

**Comment by Alaneor** [comment]
It did work when reading data from ldap, yes. Not sure about writing to binary attributes - I think that was not supported here if I remember my browsing through the issues correctly.

**Comment by jeremycx** [comment]
I'm pretty sure it worked because I put the `objectGUID` in the "binary list" (either that or the client lib stopped working that way).

There doesn't seem to be **any** way of getting the type of the attribute programatically. So dumb! If we (slow, but whatev) scan the whole buffer to see if it's valid UTF-8 or not, we have two problems:

1. speed, and
2. it's possible to have a binary attribute value that is valid UTF8 data-wise, but isn't actually UTF8 data.

So I'd rather not get into that.

However, I can likely get you binary **updates** pretty easily - I just need to check to see if the update is a Buffer object or now, and do the right thing.

How about I make a JS-accessable list of binary attrs - any new attribute names you push into the list will come out as buffers after a search operation?

**Comment by jeremycx** [comment]
Thoughts: technically, if we can't actually tell if something's binary, the we should ALWAYS return a Buffer. 

I wouldn't even use this if I had to convert from Buffer() every time... ugh.

**Comment by Alaneor** [comment]
Actually that last thought is not a bad idea - the response could contain both the stringified value and some kind of `rawValue` property, where the unmodified data would be available if need be.

But the idea with a global, configurable list of known binary properties is also quite usable.

**Comment by jeremycx** [comment]
This is still planned, but back-burnery.
