### ISSUE TITLE
Search callback not being called

### ISSUE THREAD

**Issue by throwaway47** [jeremycx/node-LDAP#55]
I am doing a very basic search against my Microsoft AD, and am having this strange problem.  If I specify an OU in the base of the search object, the callback is called wether it finds an entry or not.  If I don't specify an OU my callback function is never called, but what is strange is I see the server sending back a response with the found object (using netmon).

Just incase my ramblings don't make sense.
base: 'ou=office,dc=test,dc=local'  - works as expected
base: 'dc=test,dc=local'  - has the issue

**Comment by jeremycx** [comment]
New 3.x.x should work better. Closing.
