### ISSUE TITLE
Node v0.12.1 install/compile error

### ISSUE THREAD

**Issue by Enrico204** [jeremycx/node-LDAP#70]
I'm trying to install latest LDAP (even pointing directly to git repo) with npm and it fails with an error:

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ebassetti/.nodelocal/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/home/ebassetti/.nodelocal/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ebassetti/IdeaProjects/UnitIntranet2/node_modules/LDAP
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/home/ebassetti/.nodelocal/bin/node" "/home/ebassetti/.nodelocal/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

Also there are a bunch of errors from compilation process: http://nopaste.linux-dev.org/?452926

I tried to fix that but I've no knowledge on node libraries :-(

**Comment by Alaneor** [comment]
The v8 C API has changed dramatically in Node.js 0.12 compared to 0.10. Unfortunately, adaptation of the code would require epic refactoring of the C codebase...

Perhaps the [NaN](https://github.com/rvagg/nan) library might be useful in such process if keeping this library backwards-compatible with Node.js 0.10 is desirable.

My C-Fu is rather non-existent so I am of very little practical assistance here...:(

**Comment by jeremycx** [comment]
Yeah, conversion to NaN is on my TODO list -- I use node-LDAP in production, so it will happen eventually, but likely not until this crunch is over.

**Comment by jeremycx** [comment]
New version.
