### ISSUE TITLE
Binary data update?

### ISSUE THREAD

**Issue by syadykin** [jeremycx/node-LDAP#71]
Hello.
I tried to add/update binary attributes in LDAP without any luck — i have corrupted data stored in jpegPhoto attribute on the ldap side.

Looking to the code makes me think there is no support for binary data in modify/add methods yet. Is it correct?

**Comment by Alaneor** [comment]
Are you setting the value of the attribute to a `Buffer`...? Perhaps you could share your code with us so we can take a look?

**Comment by syadykin** [comment]
Yes, i'm setting the value to buffer as well, here is the dump of changes structure:

    [ {
        op: 'replace',
        attr: 'jpegPhoto',
        vals: [ <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 01 00 48 00 48 00 00 ff db 00 43 00 06 04 05 06 05 04 06 06 05 06 07 07 06 08 0a 10 0a 0a 09 09 0a 14 0e 0f 0c 10 ...> ]
    } ]

The code is pretty complex. Incoming value is base64 encoded so i'm creating a value with:

    …
    vals: [new Buffer(value, 'base64')]
    …

After update i get 

    jpegPhoto: [ <Buffer ef bf bd ef bf bd ef bf bd ef bf bd> ],

**Comment by Alaneor** [comment]
Could you also try updating the `jpegPhoto` attribute so that the attribute to be updated is specified as `jpegPhoto;binary`?

That's how this library handles **retrieving** binary attributes correctly, so perhaps it may work with updates as well. I have not tried it, though.

**Comment by syadykin** [comment]
Well `;binary` postfix is used for attributes not listed explicitly as binary in https://github.com/jeremycx/node-LDAP/blob/master/src/LDAP.cc#L701 and this is not the case i suppose.

**Comment by jeremycx** [comment]
Currently, there's no support for binary mods - the issue is line 505 of ldap.cc -- it should check for buffer, and use the binary value if so.

I need to update the library to NaN for 12.x / io.js compatibility at some point soon, and I'll try to fix this then, but in the meantime pull requests are welcome :)

**Comment by jeremycx** [comment]
Closed due to inactivity/new release.
