### ISSUE TITLE
SASL authentication

### ISSUE THREAD

**Issue by dvtylr** [jeremycx/node-LDAP#73]
Any interest in this?  I have a very rough working implementation using GSSAPI against AD/LDS.  Naturally it creates a dependency on the Cyrus SASL libraries.  It is also quite limited at the moment, only using defaults for all settings and the call is synchronous.

**Comment by jeremycx** [comment]
Github stopped notifying me of issues for some reason, and I missed this one. Apologies.

Just dropped a new 2.x.x version that's much more robust. would love to see what you have on GSSAPI.

**Comment by dvtylr** [comment]
Thanks for the reminder, I have been trying to shepherd this change through our internal processes so I could get it back to Github for a PR.  I will look to update the patch to your latest release.  We have been using the patch for a few months now with Kerberos authentication against Windows AD and LDS servers so seems to work for that use case.

**Comment by jeremycx** [comment]
Please submit a PR if you ever get the go-ahead. Closing.

**Comment by strebl** [comment]
@dvtylr Do you have new information on this issue?

**Comment by dvtylr** [comment]
It took close to a year but I now have the go ahead to release patches to open source projects.  It is now with me to update to the new API as we are on a very old version node-LDAP (and node).  I will do my best to make time for this as I would like to upgrade.  Ideally I can find some time in the next couple of weeks.  The patch will be from the bmocm user.

**Comment by strebl** [comment]
@dvtylr Thanks for your information!

**Comment by jeremycx** [comment]
Looking forward to this! Will merge the PR as soon as it drops!

**Comment by bmocm** [comment]
Implemented with #94.
