### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by dangquang1020** [jeremycx/node-LDAP#74]
When I try to modify it throw an error : Segmentation fault (core dumped) and it break my ssh connection.
How can I resolve this problem?

**Comment by Alaneor** [comment]
You have most likely recently upgraded to a newer Node version.

You need to delete your *node_modules* folder and install all dependencies again.

**Comment by dangquang1020** [comment]
Thank you for your help, I have upgraded to latest Node version and re-create new LDAP server node.
The error not occur anymore.
Thanks Alaneor :+1:
