### ISSUE TITLE
Feature request: support for query parameterization

### ISSUE THREAD

**Issue by philipb** [jeremycx/node-LDAP#75]
Rationale:https://www.owasp.org/index.php/LDAP_injection

search_options.filter could be vulnerable to untrusted input.  Depending on the application, obviously.

**Comment by jeremycx** [comment]
Got a good, complete sanitizer function handy? I'd include if I knew it was 100% correct, but am happy leaving sanitization up to the developer if not.

**Comment by jeremycx** [comment]
Included in 3.1.X
