### ISSUE TITLE
npm install on windows 10/2008R2

### ISSUE THREAD

**Issue by AntonioComiGaia** [jeremycx/node-LDAP#88]
Hi,

I get the following error during the installation ( npm i ):

>  fatal error C1083: Cannot open include file: 'ldap.h': N o such file or directory (compiling source file ..\LDAPCnx.cc)

Did I miss something?

**Comment by jeremycx** [comment]
Do you have the openldap-dev libraries installed? You need to do something like

apt-get install openldap24-dev

**Comment by jeremycx** [comment]
Crap. Didn't see the windows part of the title :)

I don't think it will compile on Windows, but you might have some luck if you have the openLDAP libraries in your include path (assuming openLDAP compiles in Windows, I don't know).

If you can get it to work, fire me a PR, and we can start supporting Windows. :)
