### ISSUE TITLE
Unable to use LDAP with angular-cli project - Please assist

### ISSUE THREAD

**Issue by shrutkirtisarode** [jeremycx/node-LDAP#97]
Windows_NT 6.1.7601
 argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
ules\\npm\\bin\\npm-cli.js" "install" "LDAP"
 node v7.7.1
 npm  v4.1.2
 code ELIFECYCLE

 LDAP@1.2.1 install: `node-gyp rebuild`
 Exit status 1

 Failed at the LDAP@1.2.1 install script 'node-gyp rebuild'.
 Make sure you have the latest version of node.js and npm installed.
 If you do, this is most likely a problem with the LDAP package,
 not with npm itself.
 Tell the author that this fails on your system:
     node-gyp rebuild
 You can get information on how to open an issue for this project with:
     npm bugs LDAP
 Or if that isn't available, you can get their info via:
     npm owner ls LDAP
 There is likely additional logging output above.

 Please include the following file with any support request:
     D:\FinanceReport\FinanceReportingClient\FinanceReporting\npm-debug.

**Comment by jeremycx** [comment]
There's no support for Windows builds at this point. Maybe you can get it to compile and submit some patches?
